[tool.mypy]
python_version = "3.11"

# Commonly used individual flags (equivalent to : strict = true)
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true
ignore_missing_imports = true
no_implicit_optional = true
disallow_untyped_defs = true
disallow_any_generics = true
check_untyped_defs = true
